=== jm-cc/pm2/doc/xml2html/data/xml/DOCUMENT.dtd
<!ELEMENT DOCUMENT (TITLE?,WML?,LABRI?,ABSTRACT,INRIA?,SECTION*,BIBLIOGRAPHY?,APPENDIX?) >
<!ATTLIST DOCUMENT TITLE CDATA #IMPLIED>
<!ATTLIST DOCUMENT AUTHOR CDATA #REQUIRED>
<!ATTLIST DOCUMENT DATE CDATA #IMPLIED>
<!ATTLIST DOCUMENT EMAIL CDATA #REQUIRED>

<!ELEMENT ABSTRACT (P*,KEYWORD?)>
<!ATTLIST ABSTRACT TABLEOFCONTENTS (true|false) "true">
<!ATTLIST ABSTRACT TABLEOFPROGRAMS (true|false) "false">

<!ELEMENT KEYWORD ANY>

<!ELEMENT WML EMPTY>
<!ATTLIST WML INCLUDE CDATA #IMPLIED>

<!ELEMENT LABRI EMPTY>
<!ATTLIST LABRI NUMBER CDATA #IMPLIED>

<!ELEMENT INRIA (RESUME)>
<!ATTLIST INRIA TITRE CDATA #REQUIRED>
<!ATTLIST INRIA NUMBER CDATA #IMPLIED>
<!ATTLIST INRIA TYPE (RR|RT) "RR">
<!ELEMENT RESUME (P*,MOTCLE?)>
<!ELEMENT MOTCLE ANY>

<!ELEMENT SECTION (TITLE?) >
<!ATTLIST SECTION TITLE CDATA #IMPLIED>
<!ATTLIST SECTION FILE CDATA #REQUIRED>
<!ATTLIST SECTION LABEL CDATA #IMPLIED>
<!ATTLIST SECTION NEWPAGE (true|false) "false">

<!ELEMENT SUBSECTION ANY >
<!ATTLIST SUBSECTION FILE CDATA #IMPLIED>
<!ATTLIST SUBSECTION TITLE CDATA #IMPLIED>
<!ATTLIST SUBSECTION LABEL CDATA #IMPLIED>
<!ATTLIST SUBSECTION NEWPAGE (true|false) "false">

<!ELEMENT SUBSUBSECTION ANY >
<!ATTLIST SUBSUBSECTION TITLE CDATA #IMPLIED>
<!ATTLIST SUBSUBSECTION LABEL CDATA #IMPLIED>

<!ELEMENT SUBSUBSUBSECTION ANY >
<!ATTLIST SUBSUBSUBSECTION TITLE CDATA #IMPLIED>
<!ATTLIST SUBSUBSUBSECTION LABEL CDATA #IMPLIED>

<!ELEMENT TITLE ANY>
<!ELEMENT TEXT ANY>
<!ELEMENT OLDTEXT ( ( NOTE | WARNING | P | SUBSECTION | SUBSUBSECTION | TASK | CODE | TABLE | IGNORE )+ ) >

<!ELEMENT P ANY>
<!ATTLIST P INDENT (true|false) "true">
<!ATTLIST P EMPTY (true|false) "false">

<!ELEMENT NOTE ANY>
<!ELEMENT WARNING ANY>

<!ELEMENT CODE (TITLE?) >
<!ATTLIST CODE FILE CDATA #REQUIRED >
<!ATTLIST CODE TITLE CDATA #IMPLIED >

<!ELEMENT PROGRAM (TITLE?) >
<!ATTLIST PROGRAM FILE CDATA #REQUIRED >
<!ATTLIST PROGRAM TITLE CDATA #IMPLIED >
<!ATTLIST PROGRAM LABEL CDATA #IMPLIED>

<!ELEMENT IMAGE (TITLE?) >
<!ATTLIST IMAGE FILE CDATA #REQUIRED >
<!ATTLIST IMAGE SCALE CDATA #IMPLIED >
<!ATTLIST IMAGE TITLE CDATA #IMPLIED >
<!ATTLIST IMAGE LABEL CDATA #IMPLIED>

<!ELEMENT HYPHEN ANY>
<!ELEMENT TT ANY>
<!ELEMENT B ANY>
<!ELEMENT EM ANY>
<!ELEMENT VERBATIM ANY>
<!ELEMENT SMALL ANY>

<!ELEMENT UL (LI+) >
<!ELEMENT OL (LI+) >
<!ELEMENT DL (DT,DD)+ >
<!ELEMENT LI ANY >
<!ELEMENT DT ANY >
<!ELEMENT DD ANY >

<!ELEMENT REF EMPTY>
<!ATTLIST REF LABEL CDATA #REQUIRED>

<!ELEMENT POUND EMPTY>
<!ELEMENT PERCENT EMPTY>
<!ELEMENT BR EMPTY>
<!ELEMENT AMPERSAND EMPTY>
<!ELEMENT LDOTS EMPTY>
<!ELEMENT BACKSLASH EMPTY>
<!ELEMENT MICROSECOND EMPTY>
<!ELEMENT SPACE EMPTY>
<!ELEMENT SHARP EMPTY>
<!ELEMENT UNDERSCORE EMPTY>
<!ELEMENT MU EMPTY>

<!ELEMENT FOOTNOTE (#PCDATA)>
<!ELEMENT APPENDIX (SECTION+)>

<!ELEMENT BIBLIOGRAPHY (BIBITEM)+ >
<!ELEMENT BIBITEM ANY>
<!ATTLIST BIBITEM LABEL CDATA #REQUIRED>
<!ELEMENT CITE EMPTY>
<!ATTLIST CITE LABEL CDATA #REQUIRED>

<!ELEMENT URL (#PCDATA)>
<!ATTLIST URL ROOT CDATA #IMPLIED>

<!ELEMENT EMAIL (#PCDATA)>

<!ELEMENT TABLE (TITLE?,TR+) >
<!ELEMENT TR (TH+|TD+)>
<!ELEMENT TH ANY>
<!ELEMENT TD ANY>
<!ATTLIST TABLE TITLE CDATA #IMPLIED >
<!ATTLIST TABLE LABEL CDATA #IMPLIED>

<!ELEMENT IGNORE ANY>
<!ELEMENT CLEARPAGE EMPTY>

=== jm-cc/pm2/nmad/protocols/proto_mpi/doc/execute.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:./xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<SUBSECTION TITLE="Basic Use">

<P>
The directory <TT>$PM2_ROOT/nmad/examples/mpi/basics</TT> contains
basic examples that can be used to test your Mad-MPI. We will go
through this section by using the program <TT>cpi.c</TT>.
</P>

<UL>
<LI>
<P>
On top of the environment variables defined in Section <REF
LABEL="variables"/>, you need to define the following environment
variable which is needed by PM2.
</P>

<CODE FILE="./code/setLeoRsh.txt"/>
</LI>

<LI>
<P>
Compile your application with <TT>mpicc</TT>.
</P>
<CODE FILE="./code/compileCpi.txt"/>
</LI>

<LI>
<P>
You need to make sure you can connect to the machines defined in your
channel using the SSH protocol. Mad-MPI applications are launched
using the PM2's mechanisms to remotely connect to the machines, this
requires a SSH access to the machines without password or pass-phrase.
You might need to change the definition of the environment variable
<TT>LEO_RSH</TT> to match the configuration of your SSH connection.
Here an example to test your configuration is working:
</P>
<CODE FILE="./code/checkSsh.txt"/>
</LI>

<LI>
<P>
We suppose for now the network configuration file
<TT>networks.cfg</TT> is present in the directory
<TT>${PM2_ROOT}/nmad/examples/mpi/</TT> as explained in Section <REF
LABEL="installMadMpi"/>. Look at the contents of that file to see
which machines you can use for your application. The machines can be
specified by:
</P>
<UL>
  <LI>
  <P>
  Using the parameter <TT>-machinefile</TT> to specify the file
  containing the list of machines you wish to use.
  </P>
  </LI>

  <LI>
  <P>
  Using a OAR reservation, the application will be launched on
  the machines reserved by OAR.
  </P>
  </LI>

  <LI>
  <P>
  By setting the environment variable <TT>MPI_HOST_FILE</TT>
  to a file containing the list of the machines you wish to use.
  </P>
  </LI>
</UL>
<CODE FILE="./code/mpiMachineFile.txt"/>
<CODE FILE="./code/mpiHostFile.txt"/>
</LI>

<LI>
<P>
Start your application using the command <TT>mpirun</TT> taking at
least in parameter the number of processes to launch by using the
standard MPI option <TT>-np</TT> and the name of the application. The
number of processes does not have to be the number of machines in the
machine file (as specified above). Mad-MPI will use a subset of these
machines, or will start more than one process per machine accordingly.
</P>
<CODE FILE="./code/executeCpi2.txt"/>
</LI>

<LI>
<P>
You should obtain an output similar to:
</P>
<CODE FILE="./code/pi.out"/>
</LI>
</UL>

<P>
<B>Remark:</B> The default behavior of Mad-MPI is to launch
processes only on the nodes specified in the channel configuration
file. No process is spawned on the local machine (unless it is listed
in the channel configuration file)
</P>

</SUBSECTION>

<SUBSECTION TITLE="Advanced Use" LABEL="advanced">

<UL>

<LI>
<P>
The default network file used for launching jobs is
<TT>${PM2_ROOT}/nmad/examples/mpi/networks.cfg</TT>. This file has to
be provided by the person installing
Mad-MPI. However, users can select another network file by defining
the environment variable <TT>MPI_NET_FILE</TT> with the location of
the new file, e.g.: 
</P>

<CODE FILE="./code/setMpiNetFile.txt"/>
</LI>

<LI>
<P>
If the machines you wish to use to run your application are
interconnected with more than 1 network, then Mad-MPI will by default
select the first network to connect the nodes. To use another network,
you can set the environment variable <TT>MPI_NMAD_PROTOCOL</TT> to
the name of this network.
</P>

<CODE FILE="./code/setMpichMadProtocol.txt"/>
</LI>

<LI>
<P>
If you wish to start your application under the debugger, you can use
the option <TT>-dbg</TT>. All the processes of the MPI application
will be launched through <TT>gdb</TT>, the GNU debugger.
</P>
<CODE FILE="./code/executeWithGdb.txt"/>
</LI>

<LI>
<P>
If you wish to start your application under valgrind, you can use
the option <TT>-valgrind</TT>.
</P>
<CODE FILE="./code/executeWithValgrind.txt"/>
</LI>

</UL>

</SUBSECTION>

<SUBSECTION TITLE="MPI Compilers">

<P>
Mad-MPI provides by default a C and C++ compiler. The C compiler is
invoked by calling <TT>mpicc</TT> and the C++ compiler by calling
<TT>mpicxx</TT>. That name was chosen instead of <TT>mpiCC</TT> to
avoid problems with operating systems not being case-sensitive.
</P>

<P>
Fortran compilers are also available by setting the PM2 flavor
accordingly. One can use the tools <TT>ezflavor</TT> or
<TT>pm2-menu-config</TT> to modify the flavor <TT>mad4-mpi</TT> (see
Section <REF LABEL="installMadMpi"/>). Setting the option
<TT>fortran_target_gfortran</TT> or <TT>fortran_target_ifort</TT> of
the module <TT>common</TT> will compile the Fortran support within
Mad-MPI. Fortran compilers can then be invoked by calling
<TT>mpif77</TT> or <TT>mpif90</TT>.
</P>

</SUBSECTION>

</TEXT>

=== jm-cc/pm2/nmad/protocols/proto_mpi/doc/developpement.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:./xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<SUBSECTION TITLE="The API">

<P>
Mad-MPI implements almost all of the functionalities of the MPI
standard. Some additional functionalities have been added to provide
users with the facilities of the underlying NewMadeleine communication
engine. The complete API is available at the following URL:
  <LATEX>\begin{quote}</LATEX>
  <URL>http://pm2.gforge.inria.fr/newmadeleine/html/group__mpi__interface.html</URL>
  <LATEX>\end{quote}</LATEX>
</P>

</SUBSECTION>

<SUBSECTION TITLE="Debugging Mad-MPI applications">

<P>
The implementation of Mad-MPI and NewMadeleine are made up of modules.
Each of these modules can be traced or logged. The PM2 flavor for
Mad-MPI first needs to be tuned to enable the tracing and debugging
facilities. That can be done easily by starting the tool <TT>ezflavor</TT>.
</P>

<CODE FILE="./code/ezflavor.txt"/>

<P>
Once the graphical interface <TT>ezflavor</TT> is started, click on
drop-down menu in the <TT>Flavors</TT> panel, select the flavor
<TT>nmad-mpi</TT> and click on the <TT>Load</TT> button in the same
panel.
</P>

<P>
The flavor is now loaded and can be modified. You can see in the
right-hand side panel <TT>Modules</TT> all the modules involved in
the implementation of Mad-MPI as well as all the options selected for
these modules.
</P>

<P>
In the toolbar menu,
select <TT>View</TT>, <TT>Common Options</TT>, <TT>Display Panel</TT>.
In the new panel <TT>Common options</TT>, tick the option <TT>Set</TT>
in the <TT>debug</TT> panel, and the option <TT>Unset</TT> in the
<TT>opt</TT> panel. By clicking on the <TT>Apply to all</TT> button,
the selection of these two options will be modified for all the
modules at once.
</P>

<P>
Click on the <TT>Save</TT> button in the <TT>Flavors</TT> panel to
record your modifications. You can now quit <TT>ezflavor</TT> by
pressing <TT>Ctrl-Q</TT>, or by selecting in the toolbar menu,
<TT>Flavor</TT>, and <TT>Quit</TT>.
</P>

<P>
You can now recompile Mad-MPI.
</P>

<CODE FILE="./code/compileMadMpi2.txt"/>

<P>
And recompile your application as explained in Section <REF
LABEL="basicUse"/>.
</P>

<CODE FILE="./code/compileCpi.txt"/>

<P>
Debug parameters allow to trace specific modules. The general format
of a debug parameter is
<TT>--debug:&lt;MODULE_NAME&gt;-&lt;TRACE_LEVEL&gt;</TT>. For example,
the debug parameter <TT>--debug:nmad-trace</TT> will display all the
trace messages within the module <TT>nmad</TT>. <B>Note that the
module must have been compiled with the option <TT>debug</TT></B>.
More debug parameters are available, you can print the list as
follows:
</P>

<CODE FILE="./code/debugregister.txt"/>

<P>
For example, if you want to trace all the calls to communications
routines made by Mad-MPI, you can speci fy the debug parameter
<TT>mpi_nmad_transfer</TT>.
</P>

<CODE FILE="./code/debugtransfer.txt"/>


</SUBSECTION>

</TEXT>

=== jm-cc/pm2/doc/Getting_started/Sources/wizarding.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:///net/cvs/runtime/usr/xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<P>
<NOTE>
  Nathalie: Parler de Madeleine et Marcel
</NOTE>
</P>

<P>
We have gathered in this section some advanced material as a reference
for the advanced user. Beginners should probably skip this section on
a first reading. 
</P>

<SUBSECTION TITLE="Thread synchronization">

<P>
PM2 provides a number of POSIX-like synchronization facilities to
synchronize the threads within a node and among remote nodes: locks,
mutexes, semaphores, conditions, barriers. The facilities which are
local to a node are provided by the Marcel thread scheduler. Remote
synchronization facilities are provided by PM2.
</P>

<SUBSUBSECTION TITLE="Locks">

<P>
The lowest level of synchronization is to temporarily disable the scheduler
at the local node. This guarantees that the successive
instructions will be issued atomically. This is done using the
<TT>pm2_freeze</TT>/<TT>pm2_unfreeze</TT> routines. These are simply wrappers for
two essential Marcel routines respectively called <TT>lock_task</TT> and
<TT>unlock_task</TT>. The <TT>lock_task</TT> routine locks a Marcel thread within
the scheduler, disabling any external interrupt. No other thread
whatsoever can be scheduled until the <TT>unlock_task</TT> has been called.
These routines may be nested. It is up to the user to guarantee proper
nesting. One has to be uttermost careful that PM2/Marcel provides no
protection against deadlock. Also, locking a task within a node
disables any progress of the daemon service threads: no message can be
received, etc. It is up to the user to guarantee that no harm may
result, for instance from overfilling communication buffers.
</P>

<PROGRAM FILE="./Progs/freeze.c" TITLE="Freezing and unfreezing the scheduler" LABEL="prog:freeze"/>

<P>
Consider Program <REF LABEL="prog:freeze"/>. The main thread spawns an even
number of threads on the local node. Each even thread increases the
shared variable <TT>counter</TT> for <TT>N</TT> times, and each odd thread decreases
it for <TT>N</TT> times, too. To emphasize that increasing and decreasing a
variable is <EM>not</EM> an atomic operation at the level of machine
code, we have written it explicitly as a Load/Add/Store series of
operations. (Observe that the variable <TT>tmp</TT> has been registered as
<TT>volatile</TT> to prevent the wise compiler to optimize our
trick!). The expected final value for <TT>counter</TT> is<SPACE/>0.  

<PROGRAM FILE="./Progs/freeze.txt"/>
</P>

<P>
It is interesting to run the program without the calls to
<TT>pm2_freeze</TT> and <TT>pm2_unfreeze</TT> routines, and see what happens.
At least on my current workstation, this yields the following result:

<PROGRAM FILE="./Progs/freeze2.txt"/>
</P>

<P>
It shows that getting interrupted in the middle of the critical section
is a relatively frequent event, which should definitely not be
overlooked by the PM2 programmer! 
</P>

</SUBSUBSECTION>

<SUBSUBSECTION TITLE="Mutexes" LABEL="sec:mutex">

<P>
Freezing is sufficient for most simple purpose, when a (short!)
sequence of actions has to be atomically issued. Yet, this does not
handle the case of sequences where the thread may get temporarily
suspended, from its own request or not. In this case, more
sophisticated facilities have to be used, for instance mutexes (for
<EM>mutual exclusion</EM>). Consider Program <REF LABEL="prog:mutex"/>, and
assume that for some reason, the thread should be suspended right in
the middle of the critical section. We simulate this by a call to the
<TT>marcel_yield</TT> routine, which yields the control back to the
scheduler and inserts back the thread into the ready list. Running the
program without any synchronization facility returns a non-null value,
even for a few iterations. A mutex has to be first initialized using
the <TT>marcel_mutex_init</TT> routine, with a number of attributes. As
usual, <TT>NULL</TT> is a sensible default in a first place.  A mutex can
afterward be acquired and released, respectively with the
<TT>marcel_mutex_lock</TT> and <TT>marcel_mutex_unlock</TT> routines.
</P>

<PROGRAM FILE="./Progs/mutex.c" TITLE="Using mutexes in PM2" LABEL="prog:mutex"/>

</SUBSUBSECTION>

<SUBSUBSECTION TITLE="Semaphores">

<P>
Marcel also provides semaphores. A semaphore can be initialized with
the <TT>marcel_sem_init</TT> routine with an initial integer value. It can
be taken with <TT>marcel_sem_P</TT>, and freed with <TT>marcel_sem_V</TT>, as
(probably?) expected.
</P>

<PROGRAM FILE="./Progs/semaphore.c" TITLE="Using semaphores in PM2" LABEL="prog:semaphore"/>

<P>
In fact, completion is just a simple wrapping for semaphore. On
initializing a completion, a semaphore is initialized, and its address
and native node are stored into a structure. Waiting for a completion
leads in issuing a <TT>marcel_sem_P</TT> on the semaphore.  Signaling
completion includes the following action: if the local node is the
same as the native node, then a call to <TT>marcel_sem_V</TT> is issued for
the semaphore; otherwise, a RPC request is issued to the native node,
with the the signaling routine as its service and the completion as
its argument. Program <REF LABEL="prog:semaphore"/> is the same as
Program <REF LABEL="prog:mutex"/>, but completions have been replaced by
explicit semaphores.
</P>

</SUBSUBSECTION>

<SUBSUBSECTION TITLE="Conditions">

<P>
Marcel finally provides conditions variables associated to mutexes,
with a Mesa-style semantics. A thread which signals a condition keeps
on running. One of the blocked threads waiting for this condition is
selected and appended to the queue of the ready to run threads. As a
consequence, <EM>users cannot be guaranteed that a thread which exits
  a wait is immediately executed</EM>. Actually, no hypothesis may be made
about the state of the thread at the time it is eventually
scheduled. This is the reason why it is necessary to encapsulate
waiting commands within <TT>while</TT> loops: the first action of a thread
which has been signaled is then to retest the condition which
commanded its waiting; if it does not hold, then it goes back to
sleep, waiting again to be signaled.
</P>

<PROGRAM FILE="./Progs/condition.c" TITLE="Using condition variables in PM2" LABEL="prog:condition"/>

<P>
In Program <REF LABEL="prog:condition"/>, we have further constrained the
shared counter to take values only between <TT>MIN_COUNTER</TT> and
<TT>MAX_COUNTER</TT>. This is done by using two condition variables
to control incrementation and decrementation, similarly to a classical
producer-consumer scheme (We have reverted to direct operations on
the <TT>counter</TT> variable to enhance readability).
</P>

<P>
A condition is declared using the <TT>marcel_cond_init</TT> routine. It
takes as arguments the condition and an attribute. As usual, <TT>NULL</TT>
is a sensible default for the attribute. Waiting on a condition makes
sense <EM>only</EM> within a critical section controlled by some mutex.
The mutex is passed to the routine <TT>marcel_cond_wait</TT> as an
additional parameter. The very first job of this routine is to acquire
the mutex. In the regular use of condition variables, the waiting
routine is called within the critical section controlled by this very
mutex, so that is it necessarily free. But it is not mandatory to do
so, though the writer cannot see any sensible example of such a
situation at this time... The condition is signaled using the
<TT>marcel_cond_signal</TT> routine. Observe this does not require any
reference to the controlling mutex. This routine wakes up exactly one
waiting thread, if any exists. Alternatively, the
<TT>marcel_cond_broadcast</TT> routine wakes up <EM>all</EM> threads waiting
on the given condition. It is also possible to specify a limit on the
time a thread should wait for a condition, using the
<TT>marcel_cond_timedwait</TT> routine. In this case, the routine returns a
<TT>ETIMEDOUT</TT> value if the thread has not been signaled within the
specify delay.
</P>

<NOTE>
  LB to RN: Please check carefully!
</NOTE>

</SUBSUBSECTION>

</SUBSECTION>

<SUBSECTION TITLE="Profiling PM2 programs" LABEL="sec:profiling">

<NOTE>
  LB: Yet to do. 
</NOTE>

</SUBSECTION>

<SUBSECTION TITLE="Miscellaneous">

<SUBSUBSECTION TITLE="Application initialization with PM2" LABEL="sec:startupfunc">

<NOTE>
  LB: Yet to do. Describe <TT>pm2_set_startup_func</TT>?
</NOTE>

</SUBSUBSECTION>

</SUBSECTION>

</TEXT>

=== jm-cc/pm2/nmad/interfaces/mpi/doc/installation.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:./xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<SUBSECTION TITLE="Getting Access to the Source Code">

<P>
<MACRO NAME="madmpi"/> files are hosted by the project PM2 on the
InriaGforge at <URL>https://gforge.inria.fr/projects/pm2/</URL>.

The source code is managed by a <TT>Subversion</TT> server hosted by
the InriaGforge. To get the source code, you need:
</P>

<OL>
<LI>
<P>
To install the client side of the software <TT>Subversion</TT> if it
is not already available on your system. The software can be obtained
from <URL>http://subversion.tigris.org/</URL>.
</P>
</LI>

<LI>
<P>
To become a member of the project <TT>pm2</TT>. For this, you first
need to get an account to the gForge server. You can then become a
member of the project by contacting one of the project administrators.
The list of the project administrators is available from the main
project page.
</P>
<P>
You can also choose to check out the project's SVN repository through
anonymous access. In this case, you do not need to become a member,
and you will have limited access to the repository.
</P>
</LI>
</OL>

<P>
More information on how to get a gForge account, to become a member of
the specified project, or on any other related task can be obtained
from the InriaGforge at <URL>https://gforge.inria.fr/</URL>. The most
important thing is to upload your public SSH key on the gForge server
(see the FAQ at
<URL>http://siteadmin.gforge.inria.fr/FAQ.html#Q6</URL> for
instructions).
</P>

</SUBSECTION>

<SUBSECTION TITLE="Prerequisites">

<P>
The following development tools are required to compile <MACRO
NAME="madmpi"/>:
</P>

<UL>
<LI>
<P>
GNU C Compiler <TT>gcc</TT> (version <TT>3.2</TT> and higher).
</P>
</LI>

<LI>
<P>
GNU <TT>make</TT> (version <TT>3.81</TT> and higher).
</P>
</LI>

<LI>
<P>
To use InfiniBand, you must get the OFED drivers stack.
</P>
</LI>
</UL>

</SUBSECTION>

<SUBSECTION TITLE="Installing PM2">

<P>
NewMadeleine and Mad-MPI install as part of the PM2 software suite.
</P>

<OL>
<LI>
<P>
Choose an installation directory for PM2, and set the environment
variable <TT>PM2_ROOT</TT> to this directory.
</P>
<CODE FILE="./code/setenvPm2.txt"/>
</LI>

<LI>
<P>
Go in the parent directory of the directory <TT>PM2_ROOT</TT> and
check out the latest version from the <TT>Subversion</TT> server
</P>
  <UL>
  <LI>
  <P>
  using the anonymous access.
  </P>
  <CODE FILE="./code/svnPm2anon.txt"/>
  </LI>
  <LI>
  <P>
  or using your gForge account.
  </P>
  <CODE FILE="./code/svnPm2.txt"/>
  </LI>
  </UL>

<P>
You should end up with a directory named <TT>pm2</TT>.
</P>
</LI>

<LI>
<P>
You need to add to your <TT>PATH</TT> the directory <TT>pm2/bin</TT>.
</P>

<CODE FILE="./code/setPath.txt"/>
</LI>

<LI>
<P>
PM2 is installed.
</P>
</LI>
</OL>

</SUBSECTION>


<SUBSECTION TITLE="Network Protocols" LABEL="networkProtocols">

<P>
<B>
This section can be ignored if you plan to use the TCP protocol
only.
</B>
</P>

<P>
By default, the flavor for Mad-MPI only enables the TCP network
protocol. To enable more protocols such as MX or Quadrics, you need
to modify the flavor. This can be done easily by starting the tool
<TT>ezflavor</TT>. 
</P>

<CODE FILE="./code/ezflavor.txt"/>

<P>
Once the graphical interface <TT>ezflavor</TT> is started, click on
drop-down menu in the <TT>Flavors</TT> panel, select the flavor
<TT>nmad-mpi</TT> and click on the <TT>Load</TT> button in the same
panel.
</P>

<P>
The flavor is now loaded and can be modified. You can see in the
right-hand side panel <TT>Modules</TT> all the modules involved in
the implementation of Mad-MPI as well as all the options selected for
these modules.
</P>

<P>
In the <TT>Modules</TT> panel, select the <TT>nmad</TT> tab, the
options for this module will show up in the underneath panel. By using
the scrollbar on the right-hand side of this panel, you can scroll
down to the section showing the network protocols. Select the ones
which are available to you.
</P>

<P>
Click on the <TT>Save</TT> button in the <TT>Flavors</TT> panel to
record your modifications. You can now quit <TT>ezflavor</TT> by
pressing <TT>Ctrl-Q</TT>, or by selecting in the toolbar menu,
<TT>Flavor</TT>, and <TT>Quit</TT>.
</P>

</SUBSECTION>


</TEXT>

=== jm-cc/pm2/nmad/interfaces/mpi/doc/developpement.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:./xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<SUBSECTION TITLE="The API">

<P>
Mad-MPI implements almost all of the functionalities of the MPI
standard. Some additional functionalities have been added to provide
users with the facilities of the underlying NewMadeleine communication
engine. The complete API is available at the following URL:
  <LATEX>\begin{quote}</LATEX>
  <URL>http://pm2.gforge.inria.fr/newmadeleine/html/group__mpi__interface.html</URL>
  <LATEX>\end{quote}</LATEX>
</P>

</SUBSECTION>

<SUBSECTION TITLE="Debugging Mad-MPI applications">
<UL>
<LI>
<P>
If you wish to start your application under the debugger, you can use
the option <TT>-d</TT>. All the processes of the MPI application
will be launched through <TT>gdb</TT>, the GNU debugger.
</P>
<CODE FILE="./code/executeWithGdb.txt"/>
</LI>

<LI>
<P>
If you wish to start your application under valgrind, you can use
the option <TT>-valgrind</TT>.
</P>
<CODE FILE="./code/executeWithValgrind.txt"/>
</LI>
</UL>

</SUBSECTION>


</TEXT>

=== jm-cc/pm2/nmad/protocols/proto_mpi/doc/madMpiDoc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DOCUMENT SYSTEM "file:./xml2html/data/xml/DOCUMENT.dtd">
<DOCUMENT TITLE="Mad-MPI: Installation and User's Guide" AUTHOR="Nathalie Furmento" EMAIL="runtime@labri.fr">

<WML INCLUDE="my_macros.txt"/>

<ABSTRACT>
<P>
  Mad-MPI is a light implementation of the MPI standard. This simple,
  straightforward proof-of-concept implementation is a subset of the
  MPI API, that allows MPI applications to benefit from the NewMadeleine
  communication engine. Mad-MPI is based on the point-to-point
  nonblocking posting (<TT>isend</TT>, <TT>irecv</TT>) and completion
  (<TT>wait</TT>, <TT>test</TT>) operations of MPI, these four
  operations being directly mapped to the equivalent operations of
  NewMadeleine.
</P>
<P>
  Mad-MPI also implements some optimizations mechanisms for derived
  datatypes. MPI derived datatypes deal with noncontiguous memory
  locations. The advanced optimizations of NewMadeleine allowing to
  reorder packets lead to a significant gain when sending and
  receiving data based on derived datatypes.
</P>
<P>
  The latest version of this document is available from the following
  URL: <URL>http://runtime.futurs.inria.fr/MadMPI/doc/</URL>.
</P>
</ABSTRACT>

<SECTION TITLE="Installating Mad-MPI" FILE="./installation.xml" LABEL="installation" NEWPAGE="true"/>

<SECTION TITLE="Running MPI Applications" FILE="./execute.xml" LABEL="execute" NEWPAGE="true"/>

</DOCUMENT>

=== jm-cc/pm2/doc/Getting_started/Sources/appendicing.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:///net/cvs/runtime/usr/xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<SUBSECTION TITLE="Using a standard main" LABEL="sec:tradimain">

<P>
Some application may require to use the traditional <TT>main</TT> function
name instead of the regular <TT>pm2_main</TT>. This can be enabled through
the <TT>standard_main</TT> options of the Marcel flavors. This option
defines the <TT>STANDARD_MAIN</TT> compilation flag, to be used for each of
the PM2 programs. Note that this may affect the performance of several
thread management functions. The user is therefore discouraged to do
this unless explicitly required.
</P>

</SUBSECTION>

<SUBSECTION TITLE="Synopsis of PM2 scripts" LABEL="sec:scripts">

<SUBSUBSECTION TITLE="pm2conf">

<CODE FILE="./Sources/code/pm2confhelp.txt"/>

<P>
A typical use of the extended options could thus be:

<CODE FILE="./Sources/code/pm2confhelp2.txt"/>
</P>

</SUBSUBSECTION>

<SUBSUBSECTION TITLE="pm2load">

<CODE FILE="./Sources/code/pm2loadhelp.txt"/>

<NOTE>
  LB to RN: The -L option does not seem to work properly
</NOTE>

</SUBSUBSECTION>

</SUBSECTION>

<SUBSECTION TITLE="Common Pitfalls" LABEL="sec:commonpitfalls">

<P>
Table <REF LABEL="tbl:pitfalls"/> sums up the symptoms together with
possible solutions.
</P>

<TABLE TITLE="Common Pitfalls" LABEL="tbl:pitfalls">
<TR>
<TH>Symptoms</TH> <TH>Solutions</TH>
</TR>
<TR>
<TD> <TT>Permission denied</TT> error at load time </TD>
<TD> Each configuration node must be made accessible by <TT>rsh</TT> from the local host: update your <TT>.rhosts</TT> file</TD>
</TR>
</TABLE>

</SUBSECTION>

<SUBSECTION TITLE="Frequently asked questions" LABEL="sec:faq">

<P>
<EM>
  Why do I get the message "Permission denied" when running pm2load?
  
  Why does my program crash the entire cluster?
</EM>

</P>

</SUBSECTION>

</TEXT>
