=== jm-cc/pm2/doc/xml2html/data/xml/DOCUMENT.dtd
<!ELEMENT DOCUMENT (TITLE?,WML?,LABRI?,ABSTRACT,INRIA?,SECTION*,BIBLIOGRAPHY?,APPENDIX?) >
<!ATTLIST DOCUMENT TITLE CDATA #IMPLIED>
<!ATTLIST DOCUMENT AUTHOR CDATA #REQUIRED>
<!ATTLIST DOCUMENT DATE CDATA #IMPLIED>
<!ATTLIST DOCUMENT EMAIL CDATA #REQUIRED>

<!ELEMENT ABSTRACT (P*,KEYWORD?)>
<!ATTLIST ABSTRACT TABLEOFCONTENTS (true|false) "true">
<!ATTLIST ABSTRACT TABLEOFPROGRAMS (true|false) "false">

<!ELEMENT KEYWORD ANY>

<!ELEMENT WML EMPTY>
<!ATTLIST WML INCLUDE CDATA #IMPLIED>

<!ELEMENT LABRI EMPTY>
<!ATTLIST LABRI NUMBER CDATA #IMPLIED>

<!ELEMENT INRIA (RESUME)>
<!ATTLIST INRIA TITRE CDATA #REQUIRED>
<!ATTLIST INRIA NUMBER CDATA #IMPLIED>
<!ATTLIST INRIA TYPE (RR|RT) "RR">
<!ELEMENT RESUME (P*,MOTCLE?)>
<!ELEMENT MOTCLE ANY>

<!ELEMENT SECTION (TITLE?) >
<!ATTLIST SECTION TITLE CDATA #IMPLIED>
<!ATTLIST SECTION FILE CDATA #REQUIRED>
<!ATTLIST SECTION LABEL CDATA #IMPLIED>
<!ATTLIST SECTION NEWPAGE (true|false) "false">

<!ELEMENT SUBSECTION ANY >
<!ATTLIST SUBSECTION FILE CDATA #IMPLIED>
<!ATTLIST SUBSECTION TITLE CDATA #IMPLIED>
<!ATTLIST SUBSECTION LABEL CDATA #IMPLIED>
<!ATTLIST SUBSECTION NEWPAGE (true|false) "false">

<!ELEMENT SUBSUBSECTION ANY >
<!ATTLIST SUBSUBSECTION TITLE CDATA #IMPLIED>
<!ATTLIST SUBSUBSECTION LABEL CDATA #IMPLIED>

<!ELEMENT SUBSUBSUBSECTION ANY >
<!ATTLIST SUBSUBSUBSECTION TITLE CDATA #IMPLIED>
<!ATTLIST SUBSUBSUBSECTION LABEL CDATA #IMPLIED>

<!ELEMENT TITLE ANY>
<!ELEMENT TEXT ANY>
<!ELEMENT OLDTEXT ( ( NOTE | WARNING | P | SUBSECTION | SUBSUBSECTION | TASK | CODE | TABLE | IGNORE )+ ) >

<!ELEMENT P ANY>
<!ATTLIST P INDENT (true|false) "true">
<!ATTLIST P EMPTY (true|false) "false">

<!ELEMENT NOTE ANY>
<!ELEMENT WARNING ANY>

<!ELEMENT CODE (TITLE?) >
<!ATTLIST CODE FILE CDATA #REQUIRED >
<!ATTLIST CODE TITLE CDATA #IMPLIED >

<!ELEMENT PROGRAM (TITLE?) >
<!ATTLIST PROGRAM FILE CDATA #REQUIRED >
<!ATTLIST PROGRAM TITLE CDATA #IMPLIED >
<!ATTLIST PROGRAM LABEL CDATA #IMPLIED>

<!ELEMENT IMAGE (TITLE?) >
<!ATTLIST IMAGE FILE CDATA #REQUIRED >
<!ATTLIST IMAGE SCALE CDATA #IMPLIED >
<!ATTLIST IMAGE TITLE CDATA #IMPLIED >
<!ATTLIST IMAGE LABEL CDATA #IMPLIED>

<!ELEMENT HYPHEN ANY>
<!ELEMENT TT ANY>
<!ELEMENT B ANY>
<!ELEMENT EM ANY>
<!ELEMENT VERBATIM ANY>
<!ELEMENT SMALL ANY>

<!ELEMENT UL (LI+) >
<!ELEMENT OL (LI+) >
<!ELEMENT DL (DT,DD)+ >
<!ELEMENT LI ANY >
<!ELEMENT DT ANY >
<!ELEMENT DD ANY >

<!ELEMENT REF EMPTY>
<!ATTLIST REF LABEL CDATA #REQUIRED>

<!ELEMENT POUND EMPTY>
<!ELEMENT PERCENT EMPTY>
<!ELEMENT BR EMPTY>
<!ELEMENT AMPERSAND EMPTY>
<!ELEMENT LDOTS EMPTY>
<!ELEMENT BACKSLASH EMPTY>
<!ELEMENT MICROSECOND EMPTY>
<!ELEMENT SPACE EMPTY>
<!ELEMENT SHARP EMPTY>
<!ELEMENT UNDERSCORE EMPTY>
<!ELEMENT MU EMPTY>

<!ELEMENT FOOTNOTE (#PCDATA)>
<!ELEMENT APPENDIX (SECTION+)>

<!ELEMENT BIBLIOGRAPHY (BIBITEM)+ >
<!ELEMENT BIBITEM ANY>
<!ATTLIST BIBITEM LABEL CDATA #REQUIRED>
<!ELEMENT CITE EMPTY>
<!ATTLIST CITE LABEL CDATA #REQUIRED>

<!ELEMENT URL (#PCDATA)>
<!ATTLIST URL ROOT CDATA #IMPLIED>

<!ELEMENT EMAIL (#PCDATA)>

<!ELEMENT TABLE (TITLE?,TR+) >
<!ELEMENT TR (TH+|TD+)>
<!ELEMENT TH ANY>
<!ELEMENT TD ANY>
<!ATTLIST TABLE TITLE CDATA #IMPLIED >
<!ATTLIST TABLE LABEL CDATA #IMPLIED>

<!ELEMENT IGNORE ANY>
<!ELEMENT CLEARPAGE EMPTY>

=== jm-cc/pm2/doc/Getting_started/Sources/mastering.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TEXT SYSTEM "file:../xml2html/data/xml/DOCUMENT.dtd">

<TEXT>

<SUBSECTION TITLE="Mastering Marcel">

<P>
Marcel has some functionalities which are disabled by default: 

<UL>
<LI> The support of the <TT>atexit</TT> function,</LI>
<LI> The support of blocking system calls,</LI>
<LI> The support of the cleanup functions,</LI>
<LI> The support of marcel exceptions,</LI>
<LI> The support of the keys/thread-specific data handling mechanisms,</LI>
<LI> The support of the <TT>once</TT> function,</LI>
<LI> The support of the <TT>postexit</TT> function,</LI>
<LI> The support of the signals mechanism,</LI>
<LI> The support of the <TT>suspend</TT> function,</LI>
<LI> The support of the userspace mechanism.</LI>
</UL>

To enable them, you need to change your PM2 flavor by adding the options
<TT>enable_atexit</TT>,
<TT>enable_blocking</TT>,
<TT>enable_cleanup</TT>,
<TT>enable_exceptions</TT>,
<TT>enable_keys</TT>,
<TT>enable_once</TT>,
<TT>enable_postexit</TT>,
<TT>enable_signals</TT>,
<TT>enable_suspend</TT>,
or <TT>enable_userspace</TT>.
</P>

<P>
Marcel can be made to use part of the machine's processors: adding
<TT>--marcel-nvp 4</TT> to the command line will make it use only 4 processors.
By default, Marcel tries to <I>spread</I> over the machine, i.e. when using 4
processors of a quad-quad core machine, it will use one core of each of the 4
dies. To use <I>adjacent</I> processors, append <TT>--marcel-cpustride 1</TT>
to the command line. Eventually, appending the <TT>--marcel-firstcpu 4</TT>
option makes Marcel use processors from the fifth processor. For instance, on a
quad-quad core machine, one could run 4 Marcel applications this way:

<UL>
<LI>appli1 --marcel-nvp 4 --marcel-cpustride 1 --marcel-firstcpu 0
<LI>appli2 --marcel-nvp 4 --marcel-cpustride 1 --marcel-firstcpu 4
<LI>appli3 --marcel-nvp 4 --marcel-cpustride 1 --marcel-firstcpu 8
<LI>appli4 --marcel-nvp 4 --marcel-cpustride 1 --marcel-firstcpu 12
</UL>

Each application will get bound to a die.
</P>

<P>
Other Marcel options are available, append <TT>--marcel-help</TT> to the command line to get some help.
</P>

</SUBSECTION>

</TEXT>

=== jm-cc/pm2/doc/Getting_started/start.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DOCUMENT SYSTEM "file:../xml2html/data/xml/DOCUMENT.dtd">
<DOCUMENT TITLE="Getting started with PM2"
          AUTHOR="The PM2 Team" EMAIL="runtime@labri.fr">
<!-- AUTHOR="Olivier Aumage and Gabriel Antoniu and Luc Bougé and Vincent Danjean and Raymond Namyst" EMAIL="runtime@labri.fr" -->

<!-- DATE="December 2005" -->

<WML INCLUDE="my_macros.txt"/>

<LABRI/> <!-- NUMBER="RR-1375-05" -->

<ABSTRACT TABLEOFPROGRAMS="true">
<P>
PM2 (<EM>Parallel Multithreaded Machine</EM>) is a distributed
multithreaded programming environment designed to efficiently support
irregular parallel applications on distributed architectures of SMP
nodes. This manual presents an installer's, user's and developer's guide for
 PM2.
</P>
<P>
If you have any questions concerning PM2, please, send an email to
 <EMAIL>pm2-users@lists.gforge.inria.fr</EMAIL>. However, please first
 make sure that your problem is not already listed in the
 <EM>Frequently Asked   Questions</EM> Section <REF LABEL="sec:faq"/>.
</P>
<P>
  The latest version of this document is available from the following
  URL:
  <LATEX>\begin{quote}</LATEX>
  <URL>http://runtime.futurs.inria.fr/pm2-doc/</URL>
  <LATEX>\end{quote}</LATEX>
</P>
<KEYWORD>RPC, Communication, Thread, Distributed Programming.</KEYWORD>
</ABSTRACT>

<INRIA TYPE="RT" TITRE="Démarrer avec PM2">
<RESUME>
<MOTCLE></MOTCLE>
</RESUME>
</INRIA>

<SECTION TITLE="Introducing PM2" FILE="./Sources/introduction.xml" LABEL="introduction" NEWPAGE="true"/>

<SECTION TITLE="Installing PM2" FILE="./Sources/installation.xml" LABEL="installation" NEWPAGE="true"/>

<SECTION TITLE="Discovering PM2" FILE="./Sources/discovering.xml" LABEL="discovering" NEWPAGE="true"/>

<SECTION TITLE="Customizing and debugging PM2" FILE="./Sources/customizing.xml" LABEL="customizing" NEWPAGE="true"/>

<SECTION TITLE="Mastering PM2" FILE="./Sources/mastering.xml" LABEL="mastering" NEWPAGE="true"/>

<SECTION TITLE="Wizarding PM2: advanced features" FILE="./Sources/wizarding.xml" LABEL="wizarding" NEWPAGE="true"/>

<SECTION TITLE="Additional PM2 material" FILE="./Sources/appendicing.xml" LABEL="appendicing" NEWPAGE="true"/>

<SECTION TITLE="Reading on PM2" FILE="./Sources/reading.xml" LABEL="reading" NEWPAGE="true"/>


</DOCUMENT>
